name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.2
      with:
        cli: 1.10.1.693 # Clojure CLI based on tools.deps

    - name: Execute clojure code on Linux and MacOS
      if: ${{ matrix.os != 'windows-latest' }}
      run: clojure -X:test
      shell: bash
